# Create here the Drupal site you would like
version: '2'
services:
  amazeeio-ssh-agent:
    image: amazeeio/ssh-agent
    container_name: amazeeio-ssh-agent
    restart: always
    network_mode: bridge
  amazeeio-haproxy:
    image: amazeeio/haproxy
    container_name: amazeeio-haproxy
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
      - "443:443"
