# Create here the Drupal site you would like
version: '2'
services:
  amazeeio-ssh-agent:
    image: amazeeio/ssh-agent
    container_name: amazeeio-ssh-agent
    restart: always
    network_mode: bridge
  amazeeio-haproxy:
    image: amazeeio/haproxy
    container_name: amazeeio-haproxy
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
      - "443:443"
  amazeeio-dnsmasq:
    image: andyshinn/dnsmasq:2.75
    container_name: amazeeio-dnsmasq
    restart: always
    network_mode: bridge
    command: -A 127.0.0.1
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
